### PR TITLE
Embed the BSEC library @ v1.6.1480 as a temporary workaround

### LINKED ISSUE #69: Compilation error with latest version of "BSEC Software Library" dependency: `bsec_datatypes.h: No such file or directory`
I use this board with a MKR1010 and tried to compile some examples but without luck. Both, with the official Aruino IDE and the VSC and PlatformIO it refuses to compile.
I had success compile it when I use the previous version of bsec.h (works with 1.6.1480).

With bsec.h@1.7.1492 I get this:

> In file included from c:\Users\\*USER*\Documents\Arduino\libraries\Arduino_MKRIoTCarrier\src/MKRIoTCarrierDefines.h:12:0,
>                from c:\Users\\*USER*\Documents\Arduino\libraries\Arduino_MKRIoTCarrier\src/Arduino_MKRIoTCarrier.h:25,
>                 from C:\Users\\*USER*\AppData\Local\Temp\.arduinoIDE-unsaved202314-13184-jf53iv.t4jn\ReadPressure>\ReadPressure.ino:14:
>c:\Users\\*USER*\Documents\Arduino\libraries\BSEC_Software_Library\src/bsec.h:46:10: fatal error: bsec_datatypes.h: No such file or >directory
 >#include "bsec_datatypes.h"
 >         ^~~~~~~~~~~~~~~~~~
>compilation terminated.
>
>exit status 1
>
>Compilation error: exit status 1

### PR DESCRIPTION
**Pull request by alranel**
With this PR we're embedding the BSEC library at the latest working version, as a temporary workaround until the upstream library is updated.

Fixes #69

### CODE REVIEW

File: src/bsec/inc/bsec_datatypes.h [hunk 1]
```diff
@@ -0,0 +1,489 @@
...
+
+#define BSEC_MAX_WORKBUFFER_SIZE     (2048)    /*!< Maximum size (in bytes) of the work buffer */
+#define BSEC_MAX_PHYSICAL_SENSOR     (8)         /*!< Number of physical sensors that need allocated space before calling bsec_update_subscription() */
+#define BSEC_MAX_PROPERTY_BLOB_SIZE  (454)     /*!< Maximum size (in bytes) of the data blobs returned by bsec_get_configuration() */
+#define BSEC_MAX_STATE_BLOB_SIZE     (139)        /*!< Maximum size (in bytes) of the data blobs returned by bsec_get_state()*/
+#define BSEC_SAMPLE_RATE_DISABLED    (65535.0f)      /*!< Sample rate of a disabled sensor */
+#define BSEC_SAMPLE_RATE_ULP         (0.0033333f)           /*!< Sample rate in case of Ultra Low Power Mode */
+#define BSEC_SAMPLE_RATE_CONTINUOUS  (1.0f)    /*!< Sample rate in case of Continuous Mode */ 
+#define BSEC_SAMPLE_RATE_LP          (0.33333f)            /*!< Sample rate in case of Low Power Mode */
+#define BSEC_SAMPLE_RATE_ULP_MEASUREMENT_ON_DEMAND         (0.0f)            /*!< Input value used to trigger an extra measurment (ULP plus) */
```
Comment (marqdevx) [inline src/bsec/inc/bsec_datatypes.h:95]:
```suggestion
#define BSEC_SAMPLE_RATE_ULP_MEASUREMENT_ON_DEMAND         (0.0f)            /*!< Input value used to trigger an extra measurement (ULP plus) */        

```

**Review by marqdevx — APPROVED** [review]

File: src/bsec/inc/bsec_datatypes.h (hunk 1 above)
Comment (per1234) [reply src/bsec/inc/bsec_datatypes.h:95]: An alternative would be to configure the spellcheck to skip `./src/bsec` by adding that path to the `skip` field of a `.codespellrc` [configuration file](https://github.com/codespell-project/codespell#using-a-config-file).

Typically a `.codespellrc` file is added to the repo at the time the workflow is installed, but I see it is not currently present in this repo. The standardized base file used in Arduino repositories is available here:

https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/spell-check/.codespellrc

Comment (alranel) [reply src/bsec/inc/bsec_datatypes.h:95]: Good idea @per1234, I added a .codespellrc to skip parsing that directory since I'd like to avoid touching/maintaining it. We're going to remove it when the upstream lib is fixed hopefully...
